import type { Question } from "./types";

/**
 * Demo question bank — 42 questions across 6 categories.
 * This file mirrors the data in supabase/migrations/20260317000010_seed_demo_questions.sql.
 * The app fetches questions from Supabase at runtime; this file is the source of truth
 * for seeding and local reference only.
 */
export const questions: Question[] = [
  // ─── 번식학 ─────────────────────────────────────────────────────────────────
  {
    id: "q1",
    question: "포유류에서 배란을 직접 유발하는 호르몬은?",
    choices: ["FSH", "LH", "프로제스테론", "에스트로겐", "프로락틴"],
    answer: "LH",
    explanation:
      "LH(황체형성호르몬)의 급증(LH surge)이 배란을 직접 유발합니다. FSH는 난포 발달을 촉진하며, 에스트로겐은 LH surge의 양성 피드백 신호로 작용합니다.",
    category: "번식학",
    subject: "생식내분비학",
    topic: "배란",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q2",
    question: "포유류에서 수정이 주로 일어나는 부위는?",
    choices: ["자궁체", "자궁경관", "난관 팽대부", "질", "난소"],
    answer: "난관 팽대부",
    explanation:
      "수정은 난관의 팽대부(ampulla)에서 주로 일어납니다. 난관은 난소에서 자궁으로 연결되며 팽대부는 협부와 자궁 사이에 위치합니다.",
    category: "번식학",
    subject: "생식생리학",
    topic: "수정",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q3",
    question: "황체(corpus luteum)에서 주로 분비되는 호르몬은?",
    choices: ["LH", "FSH", "프로제스테론", "옥시토신", "프로락틴"],
    answer: "프로제스테론",
    explanation:
      "황체는 배란 후 파열된 난포에서 형성되며 프로제스테론을 주로 분비합니다. 프로제스테론은 자궁내막을 유지하고 임신을 지속시키는 역할을 합니다.",
    category: "번식학",
    subject: "생식내분비학",
    topic: "황체",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q4",
    question: "소(Bos taurus)의 평균 발정주기는?",
    choices: ["7일", "14일", "21일", "28일", "35일"],
    answer: "21일",
    explanation:
      "소의 발정주기는 평균 21일(18~24일)입니다. 발정 지속 시간은 약 18시간이며, 배란은 발정 종료 후 약 10~12시간에 일어납니다.",
    category: "번식학",
    subject: "발정생리학",
    topic: "발정주기",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q5",
    question: "개(Canis lupus familiaris)의 평균 임신 기간은?",
    choices: ["45일", "55일", "63일", "72일", "80일"],
    answer: "63일",
    explanation:
      "개의 임신 기간은 교배일로부터 평균 63일(60~65일)입니다. LH surge를 기준으로 하면 65일로 더 일정합니다.",
    category: "번식학",
    subject: "임신생리학",
    topic: "임신기간",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q6",
    question: "착상 직전 배아 발달 단계로 올바른 것은?",
    choices: [
      "2세포기",
      "상실배(morula)",
      "배반포(blastocyst)",
      "접합자(zygote)",
      "낭배(gastrula)",
    ],
    answer: "배반포(blastocyst)",
    explanation:
      "착상 직전 배아는 배반포 단계입니다. 배반포는 내세포괴(ICM)와 영양막(trophoblast)으로 구성되며, 영양막이 자궁내막에 착상합니다.",
    category: "번식학",
    subject: "발생학",
    topic: "착상",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q7",
    question: "정자 형성 과정이 일어나는 부위는?",
    choices: ["부고환", "정관", "정낭", "정세관", "전립선"],
    answer: "정세관",
    explanation:
      "정자형성(spermatogenesis)은 고환 내 정세관(seminiferous tubule)에서 일어납니다. 완성된 정자는 부고환으로 이동해 성숙하고 저장됩니다.",
    category: "번식학",
    subject: "웅성생식학",
    topic: "정자형성",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },

  // ─── 해부학 ─────────────────────────────────────────────────────────────────
  {
    id: "q8",
    question: "심장에서 폐로 혈액을 운반하는 혈관은?",
    choices: ["대동맥", "폐정맥", "폐동맥", "관상동맥", "대정맥"],
    answer: "폐동맥",
    explanation:
      "폐동맥은 우심실에서 폐로 산소가 부족한 혈액을 운반합니다. 폐정맥은 폐에서 좌심방으로 산소화된 혈액을 운반합니다.",
    category: "해부학",
    subject: "심혈관 해부학",
    topic: "혈관계",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q9",
    question: "성견(개)의 영구치 총 개수는?",
    choices: ["28개", "32개", "38개", "42개", "48개"],
    answer: "42개",
    explanation:
      "개의 영구치는 42개입니다: 절치 12, 견치 4, 전구치 16, 후구치 10. 유치는 28개입니다.",
    category: "해부학",
    subject: "치과 해부학",
    topic: "치식",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q10",
    question: "반추동물의 위 구획 수는?",
    choices: ["1개", "2개", "3개", "4개", "5개"],
    answer: "4개",
    explanation:
      "반추동물의 위는 제1위(반추위, rumen), 제2위(벌집위, reticulum), 제3위(겹주름위, omasum), 제4위(주름위, abomasum)의 4개 구획으로 구성됩니다.",
    category: "해부학",
    subject: "소화기 해부학",
    topic: "위",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q11",
    question: "신장의 기능적 단위는?",
    choices: ["네프론", "사구체", "세뇨관", "집합관", "신우"],
    answer: "네프론",
    explanation:
      "네프론(nephron)은 신장의 기능적 단위로, 사구체와 보우만 주머니, 세뇨관으로 구성됩니다. 개 한쪽 신장에는 약 50만~100만 개의 네프론이 있습니다.",
    category: "해부학",
    subject: "비뇨기 해부학",
    topic: "신장",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q12",
    question: "담즙을 생성하는 기관은?",
    choices: ["췌장", "비장", "간", "담낭", "소장"],
    answer: "간",
    explanation:
      "담즙은 간에서 생성됩니다. 생성된 담즙은 담낭에 저장되었다가 십이지장으로 분비되어 지방 소화와 흡수를 돕습니다.",
    category: "해부학",
    subject: "소화기 해부학",
    topic: "간",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q13",
    question: "소장에서 영양소 흡수가 주로 일어나는 부위는?",
    choices: ["위", "십이지장", "공장", "회장", "맹장"],
    answer: "공장",
    explanation:
      "소장 중 공장(jejunum)에서 영양소의 대부분이 흡수됩니다. 십이지장은 소화 효소와 담즙이 유입되는 부위이며, 회장은 비타민 B12와 담즙산을 흡수합니다.",
    category: "해부학",
    subject: "소화기 해부학",
    topic: "소장",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q14",
    question: "개에서 비장(spleen)의 주요 기능이 아닌 것은?",
    choices: [
      "혈구 저장",
      "노화 적혈구 파괴",
      "면역 반응",
      "담즙 생성",
      "조혈(태아기)",
    ],
    answer: "담즙 생성",
    explanation:
      "담즙은 간에서 생성됩니다. 비장의 주요 기능은 혈구 저장 및 방출, 노화 적혈구 파괴, 면역 반응, 태아기 조혈입니다.",
    category: "해부학",
    subject: "림프계 해부학",
    topic: "비장",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },

  // ─── 내과학 ─────────────────────────────────────────────────────────────────
  {
    id: "q15",
    question: "개 파보바이러스 장염의 특징적인 증상 조합은?",
    choices: [
      "기침과 콧물",
      "혈변과 구토",
      "발작과 실신",
      "황달과 복수",
      "다음과 다뇨",
    ],
    answer: "혈변과 구토",
    explanation:
      "개 파보바이러스(CPV-2) 장염의 특징은 심한 혈변, 구토, 탈수, 무기력증입니다. 주로 예방접종이 안 된 어린 강아지에서 발생하며 치사율이 높습니다.",
    category: "내과학",
    subject: "전염성 질환",
    topic: "바이러스성 질환",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q16",
    question: "개 쿠싱증후군(Hyperadrenocorticism)의 원인이 되는 호르몬은?",
    choices: ["인슐린", "갑상선호르몬", "코르티솔", "성장호르몬", "에피네프린"],
    answer: "코르티솔",
    explanation:
      "쿠싱증후군은 코르티솔 과잉 분비로 발생합니다. 85%는 뇌하수체 의존성(PDH), 15%는 부신 종양에 의한 부신 의존성(ADH)입니다. 다음, 다뇨, 복부팽대, 피부 변화가 특징입니다.",
    category: "내과학",
    subject: "내분비 질환",
    topic: "부신 질환",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q17",
    question: "소 제4위 전위(Displaced Abomasum)의 진단에 사용하는 청진-타진 소견은?",
    choices: [
      "마찰음",
      "유리깨지는 소리",
      "금속성 핑 소리(ping)",
      "장음 항진",
      "심잡음",
    ],
    answer: "금속성 핑 소리(ping)",
    explanation:
      "제4위 전위 시 좌측(LDA) 또는 우측(RDA) 복벽에서 청진과 동시에 타진 시 금속성 핑(ping) 소리가 들립니다. 이는 가스가 찬 제4위가 복벽에 근접했기 때문입니다.",
    category: "내과학",
    subject: "반추위 질환",
    topic: "제4위 전위",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },
  {
    id: "q18",
    question: "소 유열(Milk Fever)의 주요 원인은?",
    choices: [
      "저혈당증",
      "저칼슘혈증",
      "저마그네슘혈증",
      "저인산혈증",
      "고칼륨혈증",
    ],
    answer: "저칼슘혈증",
    explanation:
      "유열은 분만 전후 갑작스러운 칼슘 수요 증가로 인한 저칼슘혈증으로 발생합니다. 근육 마비, 기립불능, 의식 저하가 특징이며, 10% 칼슘 글루코네이트 정맥 투여로 치료합니다.",
    category: "내과학",
    subject: "대사성 질환",
    topic: "저칼슘혈증",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q19",
    question: "개 급성 췌장염의 가장 흔한 원인은?",
    choices: [
      "바이러스 감염",
      "고지방 식이",
      "복부 외상",
      "기생충 감염",
      "항생제 투여",
    ],
    answer: "고지방 식이",
    explanation:
      "개 췌장염의 가장 흔한 원인은 고지방 식이입니다. 비만, 갑작스러운 지방 과다 섭취가 위험 인자이며, 복통, 구토, 식욕 부진이 주요 증상입니다.",
    category: "내과학",
    subject: "소화기 질환",
    topic: "췌장 질환",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q20",
    question: "고양이 하부 요로계 질환(FLUTD)의 위험 인자가 아닌 것은?",
    choices: ["수컷", "비만", "실내 생활", "고단백 식이", "스트레스"],
    answer: "고단백 식이",
    explanation:
      "저단백·고탄수화물 식이, 충분하지 않은 수분 섭취가 위험 인자입니다. 수컷, 비만, 실내생활, 스트레스는 모두 위험 인자입니다. 고단백 식이는 오히려 요석 형성을 줄일 수 있습니다.",
    category: "내과학",
    subject: "비뇨기 질환",
    topic: "하부 요로계",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },
  {
    id: "q21",
    question: "개 당뇨병의 특징적인 임상 증상 조합은?",
    choices: [
      "기침, 호흡곤란",
      "다음, 다뇨, 다식, 체중감소",
      "황달, 복수, 구토",
      "발작, 실신, 허약",
      "피부병변, 탈모, 가려움증",
    ],
    answer: "다음, 다뇨, 다식, 체중감소",
    explanation:
      "당뇨병의 4대 증상은 다음(polydipsia), 다뇨(polyuria), 다식(polyphagia), 체중감소입니다. 고혈당으로 인한 삼투성 이뇨가 다뇨와 다음을 유발합니다.",
    category: "내과학",
    subject: "내분비 질환",
    topic: "당뇨병",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },

  // ─── 약리학 ─────────────────────────────────────────────────────────────────
  {
    id: "q22",
    question: "NSAIDs(비스테로이드성 소염진통제)의 주요 작용 기전은?",
    choices: [
      "히스타민 수용체 차단",
      "COX(사이클로옥시게나제) 억제",
      "도파민 수용체 차단",
      "세로토닌 재흡수 억제",
      "GABA 수용체 활성화",
    ],
    answer: "COX(사이클로옥시게나제) 억제",
    explanation:
      "NSAIDs는 아라키돈산에서 프로스타글란딘 합성에 관여하는 COX-1과 COX-2를 억제합니다. 이를 통해 소염, 진통, 해열 효과를 나타냅니다. 위장 점막 보호에 필요한 COX-1 억제가 부작용의 원인입니다.",
    category: "약리학",
    subject: "소염진통제",
    topic: "NSAIDs",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q23",
    question: "베타-락탐계 항생제(페니실린, 세팔로스포린)의 작용 기전은?",
    choices: [
      "단백질 합성 억제",
      "세포벽 합성 억제",
      "DNA 복제 억제",
      "세포막 기능 교란",
      "RNA 중합효소 억제",
    ],
    answer: "세포벽 합성 억제",
    explanation:
      "베타-락탐계 항생제는 세균의 세포벽 펩티도글리칸 합성에 관여하는 PBP(Penicillin-Binding Protein)에 결합하여 세포벽 합성을 억제합니다.",
    category: "약리학",
    subject: "항생제",
    topic: "베타-락탐계",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q24",
    question: "케타민(Ketamine)의 마취 특성으로 올바른 것은?",
    choices: [
      "근육 이완 효과가 강하다",
      "호흡 억제가 심하다",
      "해리성 마취를 유도한다",
      "서맥을 유발한다",
      "안압을 낮춘다",
    ],
    answer: "해리성 마취를 유도한다",
    explanation:
      "케타민은 NMDA 수용체 길항제로 해리성 마취(dissociative anesthesia)를 유발합니다. 통증 감각은 차단되나 의식이 완전히 소실되지 않고, 교감신경 흥분으로 심박수와 혈압이 증가합니다. 안압은 상승시킵니다.",
    category: "약리학",
    subject: "마취제",
    topic: "해리성 마취",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q25",
    question: "코르티코스테로이드 장기 투여 시 발생할 수 있는 부작용이 아닌 것은?",
    choices: [
      "의원성 쿠싱증후군",
      "면역 억제",
      "저혈당",
      "위장 궤양",
      "피부 위축",
    ],
    answer: "저혈당",
    explanation:
      "코르티코스테로이드는 당신생을 촉진하여 혈당을 상승시킵니다(고혈당). 저혈당은 인슐린 과다 투여 시 발생합니다. 나머지 보기들은 모두 코르티코스테로이드 장기 투여의 부작용입니다.",
    category: "약리학",
    subject: "호르몬제",
    topic: "코르티코스테로이드",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q26",
    question: "아트로핀(Atropine)의 주요 적응증이 아닌 것은?",
    choices: [
      "유기인 중독",
      "마취 전 투약(침샘 억제)",
      "서맥",
      "기관지 경련",
      "고혈압",
    ],
    answer: "고혈압",
    explanation:
      "아트로핀은 무스카린성 수용체 차단제입니다. 유기인 중독(콜린 과잉 증상 차단), 마취 전 분비물 억제, 서맥 치료, 기관지 확장에 사용됩니다. 고혈압 치료에는 사용하지 않습니다.",
    category: "약리학",
    subject: "자율신경계 약물",
    topic: "항콜린제",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q27",
    question: "루프 이뇨제(푸로세미드)의 주요 작용 부위는?",
    choices: [
      "근위 세뇨관",
      "헨레 루프 하행각",
      "헨레 루프 상행각",
      "원위 세뇨관",
      "집합관",
    ],
    answer: "헨레 루프 상행각",
    explanation:
      "푸로세미드(furosemide)는 헨레 루프 상행각에서 Na⁺-K⁺-2Cl⁻ 공동수송체를 억제하여 강력한 이뇨 효과를 나타냅니다. 심부전, 폐부종, 고혈압 치료에 사용됩니다.",
    category: "약리학",
    subject: "이뇨제",
    topic: "루프 이뇨제",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },
  {
    id: "q28",
    question: "오피오이드의 주요 진통 효과를 매개하는 수용체는?",
    choices: [
      "알파 수용체",
      "베타 수용체",
      "무(μ, mu) 수용체",
      "카파(κ) 수용체",
      "NMDA 수용체",
    ],
    answer: "무(μ, mu) 수용체",
    explanation:
      "오피오이드의 주요 진통 효과, 호흡 억제, 진정 효과는 주로 μ(mu) 수용체를 통해 매개됩니다. κ 수용체는 척수성 진통과 진정에, δ 수용체는 진통과 기분 조절에 관여합니다.",
    category: "약리학",
    subject: "진통제",
    topic: "오피오이드",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },

  // ─── 병리학 ─────────────────────────────────────────────────────────────────
  {
    id: "q29",
    question: "세포 손상 초기에 나타나는 가역적 변화는?",
    choices: [
      "세포 괴사",
      "세포 팽윤(water influx)",
      "세포자멸사(apoptosis)",
      "석회화",
      "섬유화",
    ],
    answer: "세포 팽윤(water influx)",
    explanation:
      "세포 손상 초기의 가역적 변화는 세포 팽윤(세포 내 수분 증가)입니다. ATP 고갈 → Na⁺/K⁺-ATPase 기능 저하 → 세포 내 Na⁺ 증가 → 삼투압에 의한 수분 유입으로 발생합니다.",
    category: "병리학",
    subject: "세포 병리학",
    topic: "세포 손상",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q30",
    question: "건락성 괴사(caseous necrosis)를 특징적으로 유발하는 질환은?",
    choices: ["경색증", "결핵", "괴저", "지방 괴사", "리케차 감염"],
    answer: "결핵",
    explanation:
      "건락성 괴사는 결핵(Mycobacterium tuberculosis/bovis)에 특징적입니다. 치즈 같은 흰색 외관을 보이며, 세포 윤곽이 소실된 무정형 호산성 물질로 나타납니다.",
    category: "병리학",
    subject: "괴사",
    topic: "건락성 괴사",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q31",
    question: "급성 화농성 염증에서 주로 관찰되는 세포는?",
    choices: ["림프구", "형질세포", "호중구", "대식세포", "호산구"],
    answer: "호중구",
    explanation:
      "급성 화농성 염증에는 호중구(neutrophil)가 주로 침윤합니다. 호중구는 최초 반응 세포로 세균 감염 시 가장 빠르게 반응하며, 사멸된 호중구가 고름(pus)을 형성합니다.",
    category: "병리학",
    subject: "염증",
    topic: "급성 염증",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q32",
    question: "악성 종양과 양성 종양을 구별하는 가장 중요한 기준은?",
    choices: ["크기", "색깔", "침윤과 전이", "성장 속도만", "표면 성상"],
    answer: "침윤과 전이",
    explanation:
      "악성 종양의 가장 중요한 특성은 침윤(invasion)과 전이(metastasis)입니다. 양성 종양은 국소적으로 성장하며 피막으로 둘러싸여 있습니다. 크기나 성장 속도만으로는 악성도를 판단할 수 없습니다.",
    category: "병리학",
    subject: "종양학",
    topic: "종양 분류",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q33",
    question: "세포자멸사(apoptosis)의 특징으로 올바른 것은?",
    choices: [
      "염증 반응을 동반한다",
      "단일 세포가 개별적으로 사멸한다",
      "세포 팽창 후 파열된다",
      "미토콘드리아 기능이 증가한다",
      "핵막이 가장 나중에 분해된다",
    ],
    answer: "단일 세포가 개별적으로 사멸한다",
    explanation:
      "아포토시스는 프로그램된 세포 사멸로 단일 세포가 개별적으로 사멸합니다. 세포 수축, 염색질 응축, 아포토시스 소체 형성이 특징이며 염증 반응을 유발하지 않습니다.",
    category: "병리학",
    subject: "세포 병리학",
    topic: "세포자멸사",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q34",
    question: "비르효(Virchow's triad)로 알려진 혈전 형성의 3대 요소가 아닌 것은?",
    choices: [
      "혈관 내피 손상",
      "혈류 이상(정체 또는 와류)",
      "혈액 과응고 상태",
      "혈소판 감소",
      "저산소증",
    ],
    answer: "혈소판 감소",
    explanation:
      "Virchow's triad는 혈관 내피 손상, 혈류 이상(정체/와류), 혈액 과응고 상태입니다. 혈소판 감소는 오히려 혈전 형성을 억제합니다. 이 세 요소가 혈전증의 병인을 설명합니다.",
    category: "병리학",
    subject: "순환 장애",
    topic: "혈전증",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },
  {
    id: "q35",
    question: "육아종성 염증(granulomatous inflammation)의 특징적인 세포는?",
    choices: [
      "호중구",
      "호산구",
      "상피유사세포(상피세포 모양의 대식세포)",
      "B림프구",
      "비만세포",
    ],
    answer: "상피유사세포(상피세포 모양의 대식세포)",
    explanation:
      "육아종은 활성화된 대식세포(상피유사세포, epithelioid cell)와 다핵 거대세포, 림프구로 구성됩니다. 결핵, 이물질, 진균 감염 등 소화하기 어려운 물질에 대한 만성 반응입니다.",
    category: "병리학",
    subject: "염증",
    topic: "육아종성 염증",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },

  // ─── 미생물학 ────────────────────────────────────────────────────────────────
  {
    id: "q36",
    question: "광견병(Rabies)의 원인체는?",
    choices: [
      "Parvovirus",
      "Lyssavirus (Rhabdovirus)",
      "Coronavirus",
      "Herpesvirus",
      "Calicivirus",
    ],
    answer: "Lyssavirus (Rhabdovirus)",
    explanation:
      "광견병은 Rhabdoviridae과 Lyssavirus속 RNA 바이러스에 의해 발생합니다. 신경 친화성이 강하며 감염된 동물의 교상을 통해 전파됩니다. 인수공통감염병입니다.",
    category: "미생물학",
    subject: "바이러스학",
    topic: "광견병",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q37",
    question: "탄저병(Anthrax)의 원인균은?",
    choices: [
      "Clostridium perfringens",
      "Bacillus anthracis",
      "Staphylococcus aureus",
      "Brucella abortus",
      "Salmonella typhimurium",
    ],
    answer: "Bacillus anthracis",
    explanation:
      "탄저병은 그람 양성 간균 Bacillus anthracis에 의해 발생합니다. 아포(내생포자)를 형성하여 환경에서 수십 년간 생존하며, 제1종 가축전염병이자 생물 테러 병원체로 분류됩니다.",
    category: "미생물학",
    subject: "세균학",
    topic: "탄저병",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q38",
    question: "개 홍역(Canine Distemper)의 원인체는?",
    choices: [
      "Parvovirus",
      "Morbillivirus (Paramyxovirus)",
      "Adenovirus",
      "Herpesvirus",
      "Coronavirus",
    ],
    answer: "Morbillivirus (Paramyxovirus)",
    explanation:
      "개 홍역은 Paramyxoviridae과 Morbillivirus속 RNA 바이러스에 의해 발생합니다. 호흡기, 소화기, 신경계를 침범하며 각막 각화증(hardpad disease)이 특징입니다.",
    category: "미생물학",
    subject: "바이러스학",
    topic: "개 홍역",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q39",
    question: "살모넬라증의 주요 전파 경로는?",
    choices: [
      "비말 감염",
      "경구 감염(오염된 음식/물)",
      "접촉 감염",
      "수직 감염",
      "절지동물 매개",
    ],
    answer: "경구 감염(오염된 음식/물)",
    explanation:
      "살모넬라증은 주로 오염된 음식(가금류, 계란, 육류)이나 물을 통한 경구 감염으로 전파됩니다. 인수공통감염병으로 사람에게도 식중독을 유발하며 보고 의무가 있습니다.",
    category: "미생물학",
    subject: "세균학",
    topic: "살모넬라증",
    difficulty: "easy",
    source: "manual",
    isActive: true,
  },
  {
    id: "q40",
    question: "소 결핵의 원인균으로 인수공통감염이 가능한 균은?",
    choices: [
      "Mycobacterium tuberculosis",
      "Mycobacterium bovis",
      "Mycobacterium avium",
      "Mycobacterium leprae",
      "Mycobacterium smegmatis",
    ],
    answer: "Mycobacterium bovis",
    explanation:
      "Mycobacterium bovis는 소 결핵의 원인균으로 사람에게도 감염됩니다. 비살균 우유 섭취가 주요 감염 경로였으나, 현재는 우유 살균으로 감소했습니다. 제2종 가축전염병입니다.",
    category: "미생물학",
    subject: "세균학",
    topic: "결핵",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
  {
    id: "q41",
    question: "구제역(FMD) 바이러스의 특성으로 올바른 것은?",
    choices: [
      "DNA 바이러스이다",
      "Picornavirus과에 속하는 RNA 바이러스이다",
      "외피(envelope)를 가진다",
      "단일 혈청형만 존재한다",
      "고양이과 동물에 주로 감염된다",
    ],
    answer: "Picornavirus과에 속하는 RNA 바이러스이다",
    explanation:
      "구제역 바이러스(FMDV)는 Picornaviridae과 Aphthovirus속 RNA 바이러스로 외피가 없습니다. 7가지 혈청형(O, A, C, SAT1, SAT2, SAT3, Asia1)이 있으며 우제류(소, 돼지 등)에 감염됩니다.",
    category: "미생물학",
    subject: "바이러스학",
    topic: "구제역",
    difficulty: "hard",
    source: "manual",
    isActive: true,
  },
  {
    id: "q42",
    question: "브루셀라증(Brucellosis)의 특징이 아닌 것은?",
    choices: [
      "인수공통감염병이다",
      "소에서 유산을 유발한다",
      "살균되지 않은 유제품으로 사람에게 감염된다",
      "고양이에서만 발생한다",
      "수컷에서 고환염을 유발한다",
    ],
    answer: "고양이에서만 발생한다",
    explanation:
      "브루셀라증은 소(B. abortus), 돼지(B. suis), 개(B. canis) 등 다양한 동물에서 발생하는 인수공통감염병입니다. 암컷에서 유산, 수컷에서 고환염/부고환염을 유발합니다.",
    category: "미생물학",
    subject: "세균학",
    topic: "브루셀라증",
    difficulty: "medium",
    source: "manual",
    isActive: true,
  },
];
