import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: "q1",
    question: "Which hormone triggers ovulation in mammals?",
    choices: ["FSH", "LH", "Progesterone", "Estrogen", "Prolactin"],
    answer: "LH",
    explanation: "Luteinising hormone surge is the key trigger for ovulation.",
    category: "Reproduction",
    subject: "Reproductive Physiology",
    topic: "Ovulation",
    difficulty: "easy",
    source: "manual",
    tags: ["hormones", "ovulation", "LH"],
    isActive: true,
  },
  {
    id: "q2",
    question: "Where does fertilisation usually occur in mammals?",
    choices: [
      "Uterine body",
      "Cervix",
      "Oviduct ampulla",
      "Vagina",
      "Ovary",
    ],
    answer: "Oviduct ampulla",
    explanation: "Fertilisation generally occurs in the ampullary region of the oviduct.",
    category: "Reproduction",
    subject: "Reproductive Physiology",
    topic: "Fertilisation",
    difficulty: "easy",
    source: "manual",
    tags: ["fertilisation", "oviduct", "ampulla"],
    isActive: true,
  },
  {
    id: "q3",
    question: "Which cell type surrounds the mammalian oocyte directly?",
    choices: [
      "Theca cells",
      "Luteal cells",
      "Granulosa cells",
      "Cumulus cells",
      "Stromal cells",
    ],
    answer: "Cumulus cells",
    explanation:
      "Cumulus cells closely surround the oocyte and form the cumulus-oocyte complex.",
    category: "Reproduction",
    subject: "Reproductive Physiology",
    topic: "Oocyte Biology",
    difficulty: "medium",
    source: "manual",
    tags: ["oocyte", "cumulus", "granulosa"],
    isActive: true,
  },
  {
    id: "q4",
    question: "Which structure connects the ovary to the uterus?",
    choices: ["Cervix", "Oviduct", "Vagina", "Endometrium", "Myometrium"],
    answer: "Oviduct",
    explanation:
      "The oviduct transports the oocyte and connects the ovary region with the uterus.",
    category: "Anatomy",
    subject: "Reproductive Anatomy",
    topic: "Female Reproductive Tract",
    difficulty: "easy",
    source: "manual",
    tags: ["anatomy", "oviduct", "ovary", "uterus"],
    isActive: true,
  },
  {
    id: "q5",
    question: "Which hormone is primarily produced by the corpus luteum?",
    choices: ["LH", "FSH", "Progesterone", "Oxytocin", "Prolactin"],
    answer: "Progesterone",
    explanation:
      "The corpus luteum primarily secretes progesterone after ovulation.",
    category: "Endocrinology",
    subject: "Reproductive Endocrinology",
    topic: "Corpus Luteum",
    difficulty: "easy",
    source: "manual",
    tags: ["corpus luteum", "progesterone", "hormones"],
    isActive: true,
  },
];
